sudo: required
os: linux
dist: xenial

language: go
go:
    - "1.12.x"

install:
  - pwd

jobs:
  include:
    - stage: All
    - script: make fmt
      name: "fmt check"
    - script: make vet
      name: "vet check"
    - script: make verify-codegen
      name: "verify whether codegen is up to date"
    - script: make test
      name: "unit test"
    - script: make reporter
      name: "build reporter"
    - script: make build
      name: "build nsq-operator"
