sudo: required
os: linux
dist: xenial

language: go
go:
    - "1.12.x"

install:
  - pwd

jobs:
  include:
    # fmt
    - script: make fmt
    # vet
    - script: make vet
    # Unit Test
    - script: make test
    # Build
    - script: make build
