apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nsqadmins.nsq.io
spec:
  group: nsq.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
  scope: Namespaced
  names:
    kind: NsqAdmin
    plural: nsqadmins
    singular: nsqadmin
    shortNames:
      - nsqadmin
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            replicas:
              type: integer
              minimum: 1
              maximum: 1024
            image:
              type: string