apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nsqdscales.nsq.io
spec:
  group: nsq.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
  scope: Namespaced
  names:
    kind: NsqdScale
    plural: nsqdscales
    singular: nsqdscale
    shortNames:
      - nsqdscale
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            qpsThreshold:
              type: integer
              minimum: 1
              maximum: 80000 # 80k
            minimum:
              type: integer
              minimum: 2 # high availability
              maximum: 1024
            maximum:
              type: integer
              minimum: 2
              maximum: 1024