apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nsqds.nsq.io
spec:
  group: nsq.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
  scope: Namespaced
  names:
    kind: Nsqd
    plural: nsqds
    singular: nsqd
    shortNames:
      - nsqd
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            replicas:
              type: integer
              minimum: 2
              maximum: 2048
            image:
              type: string
            storageClassName:
              type: string
            logMappingDir:
              type: string
            messageAvgSize:
              type: integer
              minimum: 1
              maximum: 10485760   # 10Mi
            MemoryOverBookingPercent:
              type: integer
              minimum: 0
              maximum: 100
            memoryQueueSize:
              type: integer
              minimum: 0
              maximum: 10000
            channelCount:
              type: integer
              minimum: 0
              maximum: 2048
