apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nsqlookupds.nsq.io
spec:
  group: nsq.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
  scope: Namespaced
  names:
    kind: NsqLookupd
    plural: nsqlookupds
    singular: nsqlookupd
    shortNames:
      - nsqlookupd
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            replicas:
              type: integer
              minimum: 1
              maximum: 16
            image:
              type: string
