apiVersion: apps/v1
kind: Deployment
metadata:
  name: nsq-operator
  namespace: default
spec:
  selector:
    matchLabels:
      app: nsq-operator
  replicas: 3
  template:
    metadata:
      labels:
        app: nsq-operator
    spec:
      containers:
        - name: nsq-operator
          image: dockerops123/nsq-operator:0.2.0
          imagePullPolicy: Always
          ports:
            - name: http-metrics
              containerPort: 3080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3080
            initialDelaySeconds: 4
            timeoutSeconds: 2
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3080
            initialDelaySeconds: 4
            timeoutSeconds: 2
            periodSeconds: 30
          resources:
            requests:
              cpu: "0.1"
              memory: "500Mi"
            limits:
              cpu: "0.1"
              memory: "500Mi"