apiVersion: apps/v1
kind: Deployment
metadata:
  name: nsq-operator
  namespace: default
spec:
  selector:
    matchLabels:
      app: nsq-operator
  replicas: 3
  template:
    metadata:
      labels:
        app: nsq-operator
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - nsq-operator
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: nsq-operator
          image: dockerops123/nsq-operator:0.3.0
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3080
            initialDelaySeconds: 4
            timeoutSeconds: 2
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3080
            initialDelaySeconds: 4
            timeoutSeconds: 2
            periodSeconds: 30
          resources:
            requests:
              cpu: "2"
              memory: "2Gi"
            limits:
              cpu: "2"
              memory: "2Gi"