apiVersion: "nsq.io/v1alpha1"
kind: Nsqd
metadata:
  name: test
spec:
  replicas: 2
  image: dockerops123/nsqd:1.1.0
  storageClassName: standard
  logMappingDir: /var/log/test
  messageAvgSize: 1048576   # 1Mi
  memoryQueueSize: 10000
  memoryOverSalePercent: 50
  channelCount: 0
